### ISSUE TITLE
functions created in Controller(Appctrl) in app.js is called in index.html, these functions are running twice.

### ISSUE THREAD

**Issue by ervbsankar** [ngbp/ngbp#377] opened 2015-04-23 05:22 UTC
I have used console.log to see the fucntion. I have sample function login that is called in Index.html shown below. (not able to put the code here, it is converting)
1. isLogged(login) --> is called in ng-show in a li of ul
2. isLogged(user)  --> is called in ng-hide in a li of ul
3. logutI(user) --> is called in ng-hide in a li of ul

Below is console:
executing logged login app.js:26 
executing logged user app.js:26 
executing logged logout app.js:26 
Home controller got invoked by App home.js:42 
executing logged login app.js:26 
executing logged user app.js:26 
executing logged logout app.js:26

**Comment by joshdmiller** [comment] 2015-04-23 08:04
Functions called from angular expressions (like `ngShow`) will be called _at least_ twice in every single digest in order to see if something has changed. This is a feature and not a bug. Calls from any expressions like that should always be idempotent and should usually be cheap. Otherwise you should cache the result of the call on the scope and use that.

Since this doesn't really have much to do with ngbp specifically, I'll go ahead and close this issue, but feel free to ask a follow-up and keep the conversation going.

**Closed as completed by joshdmiller** 2015-04-23 08:04 UTC
