### ISSUE TITLE
How do I keep my code up to date with ng-boilerplate

### ISSUE THREAD

**Issue by arvindtm** [ngbp/ngbp#141] opened 2013-09-13 21:34 UTC
Please forgive am asking this question on the github forum.  But need some advise.
I have been using the seed to work on my pet project. I have made several changes on top of the seed code.
How do I keep myself updated with recent changes made to the ng-boilerplate

Appreciate git commands in steps.

Thanks

**Comment by joshdmiller** [comment] 2013-09-13 23:41
Duplicate of #1. Right now, there's nothing to update. But when I release v0.3.1, I'll provide upgrade notes to make it easy.

**Closed as completed by joshdmiller** 2013-09-13 23:41 UTC
Labels: duplicate, question

**Comment by siadat** [comment] 2014-08-31 20:16
I have the same issue. Where can I find the notes for upgrading? I didn't find anything in `CHANGELOG.md` nor in `README.md`.

**Comment by joshdmiller** [comment] 2014-08-31 22:23
They're in #1. You can also try the alpha of Warlock, which will soon replace the grunt-based build of ngbp. Since it's distributed through npm, updating is easy. http://docs.getwarlock.com/#/guide/tutorial
