### ISSUE TITLE
Use ngbp in a way so you can pull future commits in your codebase.

### ISSUE THREAD

**Issue by aramalipoor** [ngbp/ngbp#293] opened 2014-08-03 14:54 UTC
I was wondering if it is possible to use _ngbp_ (or in general any boilerplate code) in a way so you pull any future commit (bugfix, feature, etc) into your codebase?

I think it depends on the boilerplate architecture! But anyway is this even a right-way to keep up with updates?

**Comment by joshdmiller** [comment] 2014-08-05 22:06
This is actually a duplicate of issue #1 - the very first issue we opened here as it was something I considered hugely important. :-)

There are some instructions there for the _general idea_, but this is actually changing. In the near future, the Grunt-based build will be superseded by [Warlock](http://getwarlock.com), which is distributed through NPM and therefore can be trivially updated.

For what it's worth, the necessity of upgrading is one of the three core reasons for creating Warlock; the git-based approach to upgrades is great only until one makes changes to the Gruntfile, at which point it becomes a veritable nightmare.

PS: Feel free to [give Warlock a try](http://docs.getwarlock.com/#/guide/getting-started) (a lot of the ancillary docs are blank for now); we don't have complete feature-parity yet, but thoughts and contributions are very welcome indeed...

**Comment by aramalipoor** [comment] 2014-08-27 14:31
Oh I didn't know about that!
I will try Warlock and contribute as much as my little knowledge can help.

I should really thank you for efforts :)

**Closed as completed** 2014-08-27 14:31 UTC
Labels: duplicate, question
