### ISSUE TITLE
Running grunt compile with grunt-ngmin causes errors

### ISSUE THREAD

**Issue by kinabalu** [ngbp/ngbp#330] opened 2014-10-10 18:59 UTC
Looks like grunt-ngmin is now deprecated and they recommend using grunt-ng-annotate.  I've updated in my codebase to use 0.4.0 of grunt-ng-annotate and everything is working much better.  Should this project update?

**Comment by manbearwiz** [comment] 2014-10-12 21:10
[This change](https://github.com/ngbp/ngbp/pull/276) is waiting to be merged already.

**Comment by nashimus** [comment] 2014-10-14 20:30
There haven't been any commits since April 15th.  Perhaps we should fork it and work on the fork.

**Comment by manbearwiz** [comment] 2014-10-14 20:49
That does look like it may be necessary, although a smoother transition would be to get some more members added to ngbp project. Any thoughts @joshdmiller, @Merott?

**Comment by PaulL1** [comment] 2014-10-14 21:17
Or take a look at warlock, which is where Josh was looking to take this next.  It has a lot of benefits, but seems a bit stalled. I suspect finishing that work (it is somewhat functional now) would be a great way to get the overall project back on track.

The biggest benefit of warlock (IMHO) is that it's upgradeable and pluggable in a similar way to how we upgrade other packages via bower - so no more cloning of github to get updates.

**Comment by manbearwiz** [comment] 2014-10-14 23:55
Just read through Warlock a bit; very interesting project. Unless I'm mistaken though, Warlock would not replace ngbp but rather be used in ngbp by replacing grunt. If that is the case, ngbp still needs maintainers going forward. Granted the duties of these maintainers would be of smaller scope once the transition to warlock is made.

**Comment by PaulL1** [comment] 2014-10-15 00:17
It should fully replace ngbp, but using gulp underneath instead of grunt. I think the issue is that Josh ran out of time, so he's not super excited about maintaining the old world, but doesn't have enough time to finish creating the new world.  A handful of contributors on warlock would probably be enough to push that over the line.  I did a little with it and it really did run better, but some of it is beyond my capabilities a bit in terms of helping to create the new (I can probably help extend on it once it's done, but not so much help built it out initially).

**Comment by joshdmiller** [comment] 2014-10-15 00:28
It's a little bit of both. Warlock will completely replace all _build-related stuff_ with ngbp, but ngbp will live on an as an example angularjs project. That is, it will just be a `warlock.json` file and the example code. Once that happens, there will be no updates except what is necessary to keep it up-to-date with future versions of Warlock, Angular, and its vendor libraries. Warlock makes this possible; with Grunt, it is not.

For this reason, @PaulL1 is right - I haven't been willing to add any new _features_ to ngbp because we're just duplicating work at that point. Bug fixes absolutely. But I haven't had a lot of time.

I would _love_ to have some additional contributors. On Warlock, we're really missing only Karma integration and a modular watch to be feature-complete with the current Grunt script. In addition, Warlock already supports many things the current grunt config does not, like SASS. @PaulL1  is also spot-on about the pluggable nature of it; we won't need to bother with so many little fixes and feature requests because the community at large will be much more involved.

All that said, if anyone wants to be a contributor to either this project or warlock (at present, I'm _not_ the only one with commit access; I'm just the owner), let me know. If you want to work on Warlock, I can get you started fairly easily, but it's a lot more complicated _internally_ because of the nature of the beast. If you want to just help out with ngbp, that's awesome too - but bug fixes and such only. I'll happily grant someone the rights to merge PRs, but we'll need to agree on those philosophical points and the PRs will need to conform to the existing coding styles - most open PRs here do not.

**Comment by PaulL1** [comment] 2014-10-15 00:37
Hmm.  If karma is the main outstanding, then I can do that.  It's probably the one bit I do know something about.  :-).  I could do protractor too whilst I was at it.

**Comment by joshdmiller** [comment] 2014-10-15 00:41
You know what? I already did Karma: https://github.com/ngbp/spell-karma. What a fun surprise!

But there's no Protractor yet - that would be a _massive_ help as it's the biggest missing feature in ngbp right now (in my opinion).

Let me dive back into my notes and see where we are. I'll post back here later tonight...

**Comment by nashimus** [comment] 2014-10-17 12:25
@joshdmiller I'm interested in being a member on both ngbp and warlock.  I'd like to merge some commits on ngbp to resolve existing issues.  I don't want to add on to ngbp, only resolve existing issues.  Also, I'd like to help get warlock rolling.  Although, I'd have to learn some to be of use with warlock, but I'm happy to do so.  Thanks!

**Comment by joshdmiller** [comment] 2014-10-17 17:46
@nashimus Yay!

For ngbp, I don't have a contributing guide, so shoot me an email (it's on my page here) and I'll put some thoughts down and then add you as a contributor. Also, let me know which ones you want to merge so I can have one last chance to comment on them if I feel I need to. :-)

As for Warlock, it's probably easier to get the interested parties together for a quick Google Hangout and talk about the current status and what we want to accomplish as a team; I have a Trello board to get us started. All who are interested should let me know and we can try to schedule something. I'd love it if we could get to an RC in a month or so. There's really not much left to do... :-)

**Comment by manbearwiz** [comment] 2014-12-08 08:30
The original issue here has been fixed in #276 so this can be closed.

**Comment by Merott** [comment] 2014-12-08 20:06
Thank you @kmb32123

**Closed as completed by Merott** 2014-12-08 20:06 UTC
