### ISSUE TITLE
Question: ui-sref not appending href as documented

### ISSUE THREAD

**Issue by micfok** [ngbp/ngbp#222] opened 2014-02-04 05:05 UTC
Hi, I know this is more of an issue with ui-router and not ngBoilerplate, but I couldn't find anyone else running into this kind of bug, so I wanted to see if it had to do with the way ngBoilerplate is set up. Essentially, I while I can access states via their urls and navigate that way, my ui-sref attributes on the anchor tags don't seem to be doing anything.

**Comment by alex6o** [comment] 2014-02-04 12:03
the problem is that ngboilerplate uses the ui router version 0.0.1 and this features was released with 0.2.0 ...

**Comment by micfok** [comment] 2014-02-04 20:20
Do you suspect that anything will break if I upgrade to 0.2.0?

**Comment by joshdmiller** [comment] 2014-02-04 20:26
Nah, should be fine. I've updated too.

**Comment by alex6o** [comment] 2014-02-04 20:29
please note that the includes have changed from 0.0.1 to 0.2.0, so you only have to include ui.router instead of ui.route and ui.state

**Comment by micfok** [comment] 2014-02-04 20:52
```
angular.module( 'ngBoilerplate', [
    'templates-app',
    'templates-common',
    'ngBoilerplate.home',
    'ngBoilerplate.about',
    // 'ui.state',
    'ui.router'
])
```

I've replaced ui.route with ui.router and now my view doesn't seem to be rendering.

**Comment by micfok** [comment] 2014-02-04 21:01
Should I add ui.router in the app modules, or should I keep them as ui.state?

**Comment by joshdmiller** [comment] 2014-02-04 21:03
As confusing as it is, `ui-route` and `ui-router` are two separate things.
The former is a directive and the latter is the actual routing system,
which used to be `ui-state`.

Are you getting an error in the console?

**Comment by micfok** [comment] 2014-02-04 21:06
Yeah, `Uncaught Error: No module: ui.router`

To clarify, I'm including ui.router in both the app declaration, and the
individual modules I use. Should this not be the case?

---

Michael Fok
780-716-1276
@micfok http://www.twitter.com/micfok

Michaelmfok@gmail.com

**Comment by joshdmiller** [comment] 2014-02-04 21:10
Requiring modules multiple times won't make a difference. `ui.route` is
part of `ui-utils`, which is a separate bower package. Are you including
that too?

**Comment by micfok** [comment] 2014-02-04 21:10
Sorry, that was `No module: ui.router`

**Comment by micfok** [comment] 2014-02-04 21:12
I was not, now I have both 'ui.route', and 'ui.router' in my main app declaration.

**Comment by joshdmiller** [comment] 2014-02-04 21:14
Is the appropriate file part of the `vendor.js`? It sounds like the file
isn't being included in the build.

**Comment by micfok** [comment] 2014-02-04 21:17
Hmmm, I know this is going to sound really dumb, but where is vendor.js? Was it a part of the ngbp package? I've updated bower.json to include the new 0.2.8 ui-router but I don't think that's what you're talking about?

**Comment by micfok** [comment] 2014-02-04 21:20
Ah, found it. Looks something like this? 

```
vendor_files: {
js: [
    'vendor/angular/angular.js',
    'vendor/angular-bootstrap/ui-bootstrap-tpls.min.js',
    'vendor/placeholders/angular-placeholders-0.0.1-SNAPSHOT.min.js',
    'vendor/angular-ui-router/release/angular-ui-router.js',
    'vendor/angular-ui-utils/modules/route/route.js'
    ],
    css: [
    ],
    assets: [
    ]
}
```

**Comment by joshdmiller** [comment] 2014-02-04 21:23
Yep. That's it; it determines which vendor files get included in the build.
Make sure the paths to the router files are right.

**Comment by micfok** [comment] 2014-02-04 21:26
Hmmm, yeah, I followed the paths there, and realized there wasn't anything in my `vendor/angular-ui-router/release/angular-ui-router.js` path. For whatever reason, bower didn't install it. Given my bower.json file below, can you see why that might be the case? Perhaps 0.2.8 isn't on bower yet? 

```
{
    "name": "ng-boilerplate",
    "version": "0.3.2",
    "devDependencies": {
        "angular": "~1.0.7",
        "angular-mocks": "~1.0.7",
        "bootstrap": "~2.3.2",
        "angular-bootstrap": "~0.3.0",
        "angular-ui-router": "~0.2.8",
        "angular-ui-utils": "~0.0.3"
    },
"dependencies": {}
}
```

**Comment by micfok** [comment] 2014-02-04 21:27
I manually downloaded file and placed it in the right place. Everything seems to be working well now! Thanks a lot Josh, you've been a lot of help.

**Comment by joshdmiller** [comment] 2014-02-04 21:30
Awesome. You should be able to get the file with bower, too.

**Closed as completed** 2014-02-04 22:03 UTC
