### ISSUE TITLE
Failed To Use Datatables

### ISSUE THREAD

**Issue by ahmadadityakj** [ngbp/ngbp#414] opened 2015-12-03 04:14 UTC
failed to integrate with angular datatable from this repo http://l-lin.github.io/angular-datatables/, when i run grunt always return error. please help me.

**Comment by joshdmiller** [comment] 2015-12-03 05:31
That is not _nearly_ enough information to help you. What files did you change and how? What's the minimum reproducible scenario? What is the error returned by grunt?

**Comment by ahmadadityakj** [comment] 2015-12-03 06:36
i include angular-datatables from bower, when i run bower install always throw "ECONFLICT Unable to find suitable version for angular". This package require angular 1.3.0+ but ngBoilerplate latest using angular 1.2. When i change to angular 1.3.0 still throw the same error. I dont have any idea why this happen. Maybe you can try and help me to solve this. Thanks

**Comment by joshdmiller** [comment] 2015-12-03 07:55
That's a bower error saying you have conflicting versions of angular between package dependencies. Try adding a `resolutions` object to your bower config with the version of angular you want to use. See [this SO answer](http://stackoverflow.com/a/25916144/259038) for an example.

I've found trying to do root cause analysis and understand what various errors actually mean and not only what the solution is but why it works has made me a far better engineer. In this case, [googling the error](https://www.google.com/search?q=ECONFLICT+Unable+to+find+suitable+version+for+angular) produces a number of results, all pointing the solution above. Googling the error is almost always the best first step.

Let me know if you have any more questions. Since this is not an ngbp issue, I'm going to close this issue though just to keep things tidy.

**Closed as completed by joshdmiller** 2015-12-03 07:55 UTC
Labels: invalid, question, more info needed
